### PR TITLE
Update node task

### PR DESCRIPTION
**Pull request by van100j**
The current node project has proved to be too simple task for us to get a better feel of the candidates' coding skills, and filter them properly.

Update the project with a more complex requirement — a RESTful API with few simple endpoints for managing players.

@pgahq/javascript

### CODE REVIEW

**Comment by silvait** [comment]
@van100j how long are we expecting it will take to complete this project?
this is supposed to be an initial screening, not the final vetting process

**Comment by van100j** [comment]
@silvait Right. This is supposed to be the initial vetting for node devs, and provide us with more details about their coding skills compared to what we've been getting so far. Inspired by the React project where they have to actually build an entire app, and we are getting much more insights about their potential. Shouldn't take them longer than an hour. 

PS: Assumed the core team is not using this, so took the liberty to update it. Let me know if you need this, I can create a new repo

**Comment by silvait** [comment]
We are using it, but if we think it will take an hour then that's fine, but longer projects will mean less applicants

**Comment by silvait** [comment]
To clarify this was supposed to be a better FizzBuzz to screen out the ppl who can barely code

**Comment by van100j** [comment]
Removing the PR in favor of https://github.com/pgahq/recruiting-api-proj

**Pull request closed without merging**
